config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  get "/auth/:provider/callback" => "sessions#create"
  delete "/logout" => "sessions#destroy", as: :logout

  resources :user_informations, only: [:new, :show, :create, :edit, :update] do
    get :list, on: :collection
  end

  resources :retirements

  resources :events, only: %i[new create show edit update destroy] do
    resources :tickets, only: %i[new create destroy]
  end
  # get 'status' => 'status#index', defaults: { format: 'json'}

  # match "*path" => "application#error404", via: :all
end

app/models/event.rb
class Event < ApplicationRecord
  has_one_attached :image, dependent: false
  has_many :tickets, dependent: :destroy

  attr_accessor :remove_image

  has_many :event_users, dependent: :destroy
  has_many :users, through: :event_users

  before_save :remove_image_if_user_accept

  # validates :image, content_type: [:png, :jpg, :jpeg],
  # size: { less_than_or_equal_to: 10.megabytes },
  # dimension: { width: { max: 2000 }, height: { max: 2000 }}

  # def created_by?(user)
  #   return false unless user
  #   owner_id == user.id
  # end

  private

  def remove_image_if_user_accept
    self.image = nil if ActiveRecord::Type::Boolean.new.cast(remove_image)
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  skip_before_action :authenticate, only: :show
  before_action :authenticate_userinfo, only: [:new, :create, :edit, :update, :destroy]
  before_action :delete_flag_event, only: [:show, :edit, :update, :destroy]
  before_action :set_event, only: [:edit, :update, :destroy]

  def show
    @event = Event.find(params[:id])
    @event_user = EventUser.find_by(params[:id])
    @userinfo = UserInformation.find_by(params[:id])
    @ticket = current_user && current_user.tickets.find_by(event: @event)
    @tickets = @event.tickets.includes(:user).order(:created_at)
  end

  def new
    #EventUserFormクラスのインスタンスの呼び出し
    @event_user_form = EventUserForm.new
  end

  def create
    @event_user_form = EventUserForm.new(event_params)
    @event_user = EventUser.new
    if current_user
      if @event_user_form.valid?
        @event_user_form.save
        redirect_to root_path, notice: "作成しました"
      else
        render :create
      end
    end
  end

  def edit
    @event_user_form = EventUserForm.new(event: @event)
  end

  def update
    @event_user_form = EventUserForm.new(event_params, event: @event)
    if @event_user_form.valid?
      @event_user_form.update_event
      redirect_to @event, notice: "更新しました"
    else
      render :update
    end
  end

  def destroy
    @event.update(delete_flag: 1)
    redirect_to root_path, notice: "削除しました"
  end

  private

  def event_params
    params.require(:event_user_form).permit(
      :name, :place, :image, :remove_image, :content, :start_at, :end_at, :owner_id, user_inoformation_id: []
    ).merge(owner_id: current_user.id)
  end

  # 自身のIDに対応するイベントを取得するメソッド
  def set_event
    if current_user
      event_id = EventUser.where(owner_id: current_user.id, event_id: params[:id]).first
      @event = Event.find(event_id.event_id)
      if @event.nil?
        redirect_to event_path, alert: "権限がありません"
      end
    else
      redirect_to root_path
    end
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/create.js.erb
document.getElementById("errors").innerHTML = "<%= j render("errors", errors: @event_user_form.errors) %>"

app/views/events/edit.html.haml
.layouts__application
  = render partial: 'shared/header'
  - now =  Time.zone.now
.container
  %h1.mt-2 イベント情報編集

  = form_with(model: @event_user_form, url: @event_user_form.persisted? ? event_path : events_path, class: "form-horizontal" ) do |f|
    #errors
    .form-group
      = f.label :name
      = f.text_field :name, class: "form-control"
    .form-group
      = f.label :place
      = f.text_field :place, class: "form-control"
    .form-group
      = f.label :start_at
      %div
        = f.datetime_select :start_at, start_year: now.year, end_year: now.year + 1
    .form-group
      = f.label :end_at
      %div
        = f.datetime_select :end_at, start_year: now.year, end_year: now.year + 1
    .form-group
      = f.label :content
      = f.text_area :content, class: "form-control", row: 10
    .form-group
      = f.label :"主催者を選択"
      = f.collection_select :user_id, UserInformation.all, :id, :display_name
    .form-group
      = f.label :image
      - if @event_user_form.image.attached? && @event_user_form.image.blob&.persisted?
        = image_tag(@event_user_form.image.variant(resize_to_fit: [200, 200]), class: 'img-thumbnail d-block mb-3')
      = f.file_field :image, class: "form-control-file"
    -# - if @event_user_form.image.attached? && @event_user_form.image.blob&.persisted?
    -#   .checkbox
    -#     %label
    -#       = f.check_box :remove_image
    -#       画像を削除する
    = f.submit class: "btn btn-primary"

    = link_to "キャンセル", root_path, class: "btn btn-secondary"
.container

app/views/events/new.html.haml
.layouts__application
  = render partial: 'shared/header'
  - now = Time.zone.now
.container
  %h1.mt-2 イベント作成

  = form_with(model: @event_user_form, url: @event_user_form.persisted? ? event_path : events_path, class: "form-horizontal" ) do |f|
    #errors
    .form-group
      = f.label :name
      = f.text_field :name, class: "form-control"
    .form-group
      = f.label :place
      = f.text_field :place, class: "form-control"
    .form-group
      = f.label :start_at
      %div
        = f.datetime_select :start_at, start_year: now.year, end_year: now.year + 1
    .form-group
      = f.label :end_at
      %div
        = f.datetime_select :end_at, start_year: now.year, end_year: now.year + 1
    .form-group
      = f.label :content
      = f.text_area :content, class: "form-control", row: 10
    .form-group
      = f.label :image
      = f.file_field :image, class: "form-control-file"
    .form-group
      = f.label :"主催者を選択"
      = javascript_pack_tag 'owner'
      = f.select :user_id, UserInformation.all.map{|o| [o.display_name, o.id]}, {include_hidden: false}, {class:'owner form-control', multiple: true}
    = f.submit class: "btn btn btn-primary"

    = link_to "キャンセル", root_path, class: "btn btn-secondary"
.container

app/views/events/show.html.haml
.layouts__application
  = render partial: 'shared/header'
.container
  %h1.mt-2.mb-2= @event.name
  .row
    .col-8
      .card.md-2
        - if @event.image.attached?
          = image_tag rails_blob_path(@event.image), class: "card-img-top"
  .card.md-2
    %h5.card-header イベント内容
    .card-body
      %p.card-text= @event.content
  .card.mb-2
    %h5.card-header 開催時間
    .card-body
      %p.card-text= "#{l(@event.start_at, format: :long)} - #{l(@event.end_at, format: :long)}"

  .card.mb-2
    %h5.card-header 開催場所
    .card-body
      %p.card-text= @event.place
  .card.mb-2
    %h5.card-header 主催者
    .card-body
      %p.card-text
      - if @userinfo.delete_flag === 0
        =  @userinfo.display_name
      - else
        退会したユーザーです
  .col-4
    - if current_user.id === @event_user.owner_id
      = link_to "イベントを編集する", edit_event_path(@event), class: "btn btn-info btn-lg btn-block"
      = link_to "イベントを削除する", event_path(@event), class: "btn btn-danger btn-lg btn-block", method: :delete, data: { confirm: "本当に削除しますか？" }
    - if @ticket
      = link_to "参加をキャンセルする", event_ticket_path(@event, @ticket), method: :delete, class: "btn btn-warning btn-lg btn-block"
    - elsif logged_in?
      %button.btn.btn-primary.btn-lg.btn-block{ "data-toggle": "modal", "data-target": "#createTicket" }
        参加する
      %div.modal.fade#createTicket
        .modal-dialog
          .modal-content
            .modal-header
              %h4.modal-title#dialogHeader 参加コメント
              %button.close{ type: "button", "data-dismiss": "modal" } &times;
            = form_with(model: @event.tickets.build, url: event_tickets_path(@event)) do |f|
              .modal-body
                #createTicketErrors
                = f.text_field :comment, class: "form-control"
              .modal-footer
                %button.btn.btn-default{ type: "button", "data-dismiss": "modal" }
                  キャンセル
                = f.button "送信", class: "btn btn-primary"
    - else
      = link_to "参加する", new_event_ticket_path(@event), class: "btn btn-primary btn-lg btn-block"

    %br
    = link_to "TOPへ戻る", root_path, class: "btn btn-secondary btn-lg btn-block"
    %hr
    .card.mb-2
      %h5.card-header 参加者
      %ul.list-group.list-group-flush
        - @tickets.each do |ticket|
          %li.list-group-item
            - if ticket.user
              = link_to(url_for_github(ticket.user), class: "card-link") do
                = image_tag ticket.user.image_url, width: 20, height: 20
                = "@#{ticket.user.name}"
              = ticket.comment
            - else
              退会したユーザーです
.container

app/views/events/update.js.erb
document.getElementById("errors").innerHTML = "<%= j render("errors", errors: @event_user_form.errors) %>"