config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  get "/auth/:provider/callback" => "sessions#create"
  delete "/logout" => "sessions#destroy", as: :logout

  resources :user_informations, only: [:new, :show, :create, :edit, :update] do
    get :list, on: :collection
  end

  resources :retirements

  resources :events, only: %i[new create show edit update destroy] do
    resources :tickets, only: %i[new create destroy]
  end
  # get 'status' => 'status#index', defaults: { format: 'json'}

  # match "*path" => "application#error404", via: :all
end

app/models/user_information.rb
class UserInformation < ApplicationRecord
  belongs_to :user

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  with_options presence: true do
    validates :display_name, length: { maximum: 255 }
    validates :display_name_eng, length: { maximum: 255 }, format: { with: /\A[a-zA-Z]+\z/}
    validates :birthday, format: { with: /\A\d{4}[-]\d{2}[-]\d{2}\z/ }
    validates :mail_address, length: { maximum: 255 }, format: { with: VALID_EMAIL_REGEX }
  end
  with_options length: { maximum: 255 } do
    validates :company
    validates :position
  end
end

app/controllers/user_informations_controller.rb
class UserInformationsController < ApplicationController
  before_action :set_user_information, only: [:show, :edit, :update]

  def list
    @userinfos = UserInformation.all
  end

  def new
    @userinfo = UserInformation.new
  end

  def create
    @userinfo = UserInformation.new(userinfo_params)
    if @userinfo.save
      redirect_to root_path, notice: "作成しました"
    end
  end

  def show
  end

  def edit
  end

  def update
    if @userinfo.update(userinfo_params)
      redirect_to @userinfo, notice: "更新しました"
    end
  end

  private

  def userinfo_params
    params.require(:user_information).permit(:display_name, :display_name_eng, :company, :birthday, :mail_address, :position, :profile).merge(user_id: current_user.id)
  end

  def set_user_information
    @userinfo = UserInformation.find(params[:id])
    binding.pry
  end
end

app/helpers/user_informations_helper.rb
module UserInformationsHelper
end

app/views/user_informations/create.js.erb
document.getElementById("errors").innerHTML = "<%= j render("errors", errors: @userinfo.errors)%>"

app/views/user_informations/edit.html.haml
.layouts__application
  = render partial: 'shared/header'
  - now =  Time.zone.now
.container
  %h1.mt-2 ユーザー情報の編集

  %br

  = form_with(model: @userinfo, class: "form-horizontal") do |f|
    #errors
    .form-group
      = f.label :表示名
      = f.text_field :display_name, class: "form-control"
    .form-group
      = f.label :表示名（英語）
      = f.text_field :display_name_eng, class: "form-control"
    .form-group
      = f.label :会社名
      = f.text_field  :company, class: "form-control", :placeholder => "※任意"
    .form-group
      = f.label :生年月日
      = f.text_field :birthday, class: "form-control"
    .form-group
      = f.label :メールアドレス
      = f.email_field  :mail_address, class: "form-control"
    .form-group
      = f.label :役職
      = f.text_field  :position, class: "form-control", :placeholder => "※任意"
    .form-group
      = f.label :プロフィール
      = f.text_area  :profile, class: "form-control", :placeholder => "※任意"
    = f.submit class: "btn btn-primary"

    = link_to "キャンセル", list_user_informations_path, class: "btn btn-secondary"
.container

app/views/user_informations/list.html.haml
.layouts__application
  = render partial: 'shared/header'
.container
  %h1.mt-2 ユーザー一覧

  %br

  %ul.list-group
    - @userinfos.each do |userinfo|
      - if (userinfo.delete_flag === 0)
        = link_to(userinfo, class: "list-group-item list-group-item-action") do
          = image_tag userinfo.user.image_url, width: 50, height: 50
          = userinfo.display_name
          = "(" + userinfo.display_name_eng + ")"
  %br
  .col-4
    = link_to "TOPへ戻る", root_path, class: "btn btn-secondary btn-lg btn-block"
.container

app/views/user_informations/new.html.haml
.layouts__application
  = render partial: 'shared/header'
  - now =  Time.zone.now
.container
  %h1.mt-2 ユーザー情報の追加

  %br

  = form_with(model: @userinfo, class: "form-horizontal") do |f|
    #errors
    .form-group
      = f.label :表示名
      = f.text_field :display_name, class: "form-control"
    .form-group
      = f.label :表示名（英語）
      = f.text_field :display_name_eng, class: "form-control"
    .form-group
      = f.label :会社名
      = f.text_field  :company, class: "form-control", :placeholder => "※任意"
    .form-group
      = f.label :生年月日
      = f.text_field  :birthday, class: "form-control",:placeholder => "yyyy-mm-dd"
    .form-group
      = f.label :メールアドレス
      = f.email_field  :mail_address, class: "form-control"
    .form-group
      = f.label :役職
      = f.text_field  :position, class: "form-control", :placeholder => "※任意"
    .form-group
      = f.label :プロフィール
      = f.text_area  :profile, class: "form-control", :placeholder => "※任意"
    = f.submit class: "btn btn-primary"

    -# = link_to "キャンセル", root_path, class: "btn btn-secondary"
.container

app/views/user_informations/show.html.haml
.layouts__application
  = render partial: 'shared/header'
.container
  %h1.mt-2 ユーザー詳細

  %br

  .row
    .col-8
      .card.mb-2
        %h5.card-header 表示名
        .card-body
          %p= @userinfo.display_name + "(" + @userinfo.display_name_eng + ")"
      .card.mb-2
        %h5.card-header 会社名
        .card-body
          %p= @userinfo.company
      .card.mb-2
        %h5.card-header 生年月日
        .card-body
          %p= @userinfo.birthday
      .card.mb-2
        %h5.card-header メールアドレス
        .card-body
          %p= @userinfo.mail_address
      .card.mb-2
        %h5.card-header 役職
        .card-body
          %p= @userinfo.position
      .card.mb-2
        %h5.card-header プロフィール
        .card-body
          %p= @userinfo.profile
      .card.mb-2
        %h5.card-header Github
        .card-body
          =image_tag @userinfo.user.image_url, width:50, height: 50
          =link_to("https://github.com/#{(@userinfo.user.name)}", class: "card-link") do
            = "@#{@userinfo.user.name}"
      .card.mb-2
        %h5.card-header ユーザーのイベント一覧
        -@userinfo.user.events.each do |event|
          - if (event.delete_flag === 0)
            .card-body
              = link_to(event, class: "card-link") do
                %h5= event.name


  %br
  .col-4
    - if current_user.id == @userinfo.user_id
      = link_to "ユーザー情報を編集する", edit_user_information_path(@userinfo), class: "btn btn-info btn-lg btn-block"
    - if logged_in?
      = link_to "ユーザー一覧へ戻る", list_user_informations_path, class: "btn btn-success btn-lg btn-block"
      = link_to "TOPへ戻る", root_path, class: "btn btn-secondary btn-lg btn-block"
.container

app/views/user_informations/update.js.erb
document.getElementById("errors").innerHTML = "<%= j render("errors", errors: @userinfo.errors)%>"